package com.neo.chat.repository;

import com.neo.chat.domain.Chat;
import com.neo.chat.domain.Message;
import com.neo.chat.domain.MessageStar;
import com.neo.chat.domain.Poll;
import com.neo.chat.domain.Post;
import com.neo.chat.domain.PushSubscription;
import com.neo.chat.domain.Session;
import com.neo.chat.domain.User;
import com.neo.chat.domain.UserExperience;
import com.neo.chat.domain.UserFeatureGrant;
import com.neo.chat.domain.UserPresence;
import com.neo.chat.domain.WeeklyMatchPick;
import com.neo.chat.enums.FeatureKey;
import com.neo.chat.enums.GrantScope;
import com.neo.chat.enums.InstallationType;
import com.neo.chat.enums.Interest;
import com.neo.chat.enums.Language;
import com.neo.chat.enums.LookingForTag;
import org.hibernate.Hibernate;
import org.hibernate.SessionFactory;
import org.hibernate.stat.Statistics;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.transaction.annotation.Transactional;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.time.Instant;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Regression coverage for the BootUI Hibernate/Database Advisor fixes (2026-09-07):
 *
 * <ul>
 *   <li>DB-SCHEMA-002 / HIB-MAP-019 — every foreign key column is the leading column of a declared
 *       index or unique constraint. The whole schema is generated by Hibernate ({@code create-drop})
 *       from the entity annotations, so this is checked against real JDBC metadata rather than by
 *       re-parsing annotations.</li>
 *   <li>HIB-QUERY-005 — the entity-returning {@code @Query} methods on {@link PostRepository} and
 *       {@link UserRepository} now {@code LEFT JOIN FETCH} their eager to-one association
 *       ({@code Post.poll}, {@code User.presence}), so Hibernate no longer issues one secondary
 *       select per returned row. Verified through {@link Statistics#getEntityFetchCount()}.</li>
 *   <li>HIB-QUERY-004 — the six former derived {@code deleteBy…} methods are now single-statement
 *       JPQL bulk deletes; they must remove exactly the rows the derived variants removed.</li>
 * </ul>
 *
 * <p>Booting the context at all also validates every new {@code @Index}: an unknown column or a
 * duplicated index name fails schema generation ({@code ddl-auto: create-drop} on H2 in the
 * {@code test} profile). The build has no {@code spring-boot-data-jpa-test} slice module, so this
 * uses the same full-context bootstrap as the controller tests; every test rolls back.
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
@TestPropertySource(properties = "spring.jpa.properties.hibernate.generate_statistics=true")
class HibernateAdvisorRegressionTest {

    @PersistenceContext
    private EntityManager em;
    @Autowired
    private DataSource dataSource;
    @Autowired
    private PostRepository postRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private UserFeatureGrantRepository userFeatureGrantRepository;
    @Autowired
    private WeeklyMatchPickRepository weeklyMatchPickRepository;
    @Autowired
    private PushSubscriptionRepository pushSubscriptionRepository;
    @Autowired
    private UserExperienceRepository userExperienceRepository;
    @Autowired
    private SessionRepository sessionRepository;
    @Autowired
    private MessageStarRepository messageStarRepository;

    private Statistics statistics;

    @BeforeEach
    void statistics() {
        statistics = em.getEntityManagerFactory().unwrap(SessionFactory.class).getStatistics();
    }

    // ── fixtures ─────────────────────────────────────────────────────────────────────

    private <T> T persist(T entity) {
        em.persist(entity);
        return entity;
    }

    private User user(String username) {
        return persist(User.builder()
                .username(username)
                .email(username + "@example.com")
                .name("User " + username)
                .isGuest(false)
                .isVerified(true)
                .build());
    }

    private UserPresence presence(User user, String status) {
        return persist(UserPresence.builder().user(user).status(status).build());
    }

    private Post post(User author, Instant expiresAt, String pollQuestion) {
        Post post = persist(Post.builder().user(author).content("hello").expiresAt(expiresAt).build());
        if (pollQuestion != null) {
            persist(Poll.builder().post(post).question(pollQuestion).build());
        }
        return post;
    }

    private Message message(User sender) {
        Chat chat = persist(Chat.builder().build());
        return persist(Message.builder().chat(chat).sender(sender).content("m").build());
    }

    /** Flush pending writes, clear the persistence context and reset Hibernate statistics. */
    private void freshContext() {
        em.flush();
        em.clear();
        statistics.clear();
    }

    // ── DB-SCHEMA-002 / HIB-MAP-019 ───────────────────────────────────────────────────

    @Test
    @DisplayName("every foreign key column is the leading column of a declared index or unique constraint")
    void everyForeignKeyHasASupportingIndex() throws Exception {
        List<String> unsupported = new ArrayList<>();
        try (Connection c = dataSource.getConnection()) {
            DatabaseMetaData md = c.getMetaData();
            List<String> tables = new ArrayList<>();
            try (ResultSet rs = md.getTables(null, "PUBLIC", "%", new String[]{"TABLE", "BASE TABLE"})) {
                while (rs.next()) {
                    tables.add(rs.getString("TABLE_NAME"));
                }
            }
            assertThat(tables).as("Hibernate generated the schema").isNotEmpty();
            for (String table : tables) {
                // FK constraint name -> ordered FK columns
                Map<String, TreeMap<Integer, String>> fks = new HashMap<>();
                try (ResultSet rs = md.getImportedKeys(null, "PUBLIC", table)) {
                    while (rs.next()) {
                        fks.computeIfAbsent(rs.getString("FK_NAME"), k -> new TreeMap<>())
                                .put(rs.getInt("KEY_SEQ"), rs.getString("FKCOLUMN_NAME").toUpperCase(Locale.ROOT));
                    }
                }
                if (fks.isEmpty()) {
                    continue;
                }
                // index name -> ordered columns. H2 silently creates its own backing index for a
                // referential constraint when none exists (named <FK_NAME>_INDEX_n); those are
                // excluded so the check reflects only what the mapping declares (what PostgreSQL gets).
                Map<String, TreeMap<Integer, String>> indexes = new HashMap<>();
                try (ResultSet rs = md.getIndexInfo(null, "PUBLIC", table, false, false)) {
                    while (rs.next()) {
                        String name = rs.getString("INDEX_NAME");
                        String col = rs.getString("COLUMN_NAME");
                        if (name == null || col == null) {
                            continue;
                        }
                        boolean h2FkBacking = fks.keySet().stream()
                                .anyMatch(fk -> name.toUpperCase(Locale.ROOT).startsWith(fk.toUpperCase(Locale.ROOT)));
                        if (h2FkBacking) {
                            continue;
                        }
                        indexes.computeIfAbsent(name, k -> new TreeMap<>())
                                .put(rs.getInt("ORDINAL_POSITION"), col.toUpperCase(Locale.ROOT));
                    }
                }
                for (Map.Entry<String, TreeMap<Integer, String>> fk : fks.entrySet()) {
                    List<String> fkCols = new ArrayList<>(fk.getValue().values());
                    boolean covered = indexes.values().stream()
                            .map(m -> new ArrayList<>(m.values()))
                            .anyMatch(idx -> idx.size() >= fkCols.size() && idx.subList(0, fkCols.size()).equals(fkCols));
                    if (!covered) {
                        unsupported.add(table + fkCols);
                    }
                }
            }
        }
        assertThat(unsupported).as("foreign keys without a supporting index").isEmpty();
    }

    // ── HIB-QUERY-005 ─────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("PostRepository fetch-joins Post.poll")
    class PostQueries {

        @Test
        void findVisibleFeedFor_loadsPollInTheSameSelect() {
            User viewer = user("viewer");
            post(viewer, null, "Q1");
            post(viewer, null, null);
            post(viewer, null, "Q3");
            freshContext();

            Page<Post> page = postRepository.findVisibleFeedFor(viewer, PageRequest.of(0, 10));

            assertThat(page.getTotalElements()).isEqualTo(3);
            assertThat(page.getContent()).hasSize(3);
            assertThat(page.getContent()).allSatisfy(p -> assertThat(Hibernate.isInitialized(p.getPoll())).isTrue());
            assertThat(page.getContent()).filteredOn(p -> p.getPoll() != null)
                    .extracting(p -> p.getPoll().getQuestion()).containsExactlyInAnyOrder("Q1", "Q3");
            assertThat(statistics.getEntityFetchCount()).as("secondary entity selects").isZero();
        }

        @Test
        void findProfileFeedFor_loadsPollInTheSameSelect() {
            User target = user("target");
            User viewer = user("viewer2");
            post(target, null, "Public poll");
            post(target, null, null);
            freshContext();

            Page<Post> page = postRepository.findProfileFeedFor(target, viewer, PageRequest.of(0, 10));

            assertThat(page.getTotalElements()).isEqualTo(2);
            assertThat(page.getContent()).allSatisfy(p -> assertThat(Hibernate.isInitialized(p.getPoll())).isTrue());
            assertThat(statistics.getEntityFetchCount()).isZero();
        }

        @Test
        void findFeedForUser_loadsPollInTheSameSelect() {
            User me = user("me");
            User stranger = user("stranger");
            post(me, null, "Mine");
            post(stranger, null, "Not followed");
            freshContext();

            Page<Post> page = postRepository.findFeedForUser(me, PageRequest.of(0, 10));

            assertThat(page.getTotalElements()).isEqualTo(1);
            assertThat(page.getContent().get(0).getPoll().getQuestion()).isEqualTo("Mine");
            assertThat(statistics.getEntityFetchCount()).isZero();
        }

        @Test
        void findExpiredActive_loadsPollInTheSameSelect() {
            User author = user("author");
            Instant now = Instant.now();
            post(author, now.minus(2, ChronoUnit.HOURS), "Expired A");
            post(author, now.minus(1, ChronoUnit.HOURS), null);
            post(author, now.plus(1, ChronoUnit.HOURS), "Still live");
            freshContext();

            List<Post> expired = postRepository.findExpiredActive(now, PageRequest.of(0, 10));

            assertThat(expired).hasSize(2);
            assertThat(expired.get(0).getPoll().getQuestion()).isEqualTo("Expired A");
            assertThat(expired.get(1).getPoll()).isNull();
            assertThat(statistics.getEntityFetchCount()).isZero();
        }
    }

    @Nested
    @DisplayName("UserRepository fetch-joins User.presence")
    class UserQueries {

        @Test
        void findAllOnlineUsersExcludeSelf_loadsPresenceInTheSameSelect() {
            User self = user("self");
            User online = user("online");
            User offline = user("offline");
            presence(self, "ONLINE");
            presence(online, "ONLINE");
            presence(offline, "OFFLINE");
            Long selfId = self.getId();
            freshContext();

            List<User> result = userRepository.findAllOnlineUsersExcludeSelf(selfId);

            assertThat(result).extracting(User::getUsername).containsExactly("online");
            assertThat(Hibernate.isInitialized(result.get(0).getPresence())).isTrue();
            assertThat(result.get(0).getPresence().getStatus()).isEqualTo("ONLINE");
            assertThat(statistics.getEntityFetchCount()).isZero();
        }

        @Test
        void findAllByUsernameInExcludeSelf_loadsPresenceInTheSameSelect() {
            User self = user("alpha");
            User other = user("beta");
            user("gamma");
            presence(other, "IDLE");
            Long selfId = self.getId();
            freshContext();

            List<User> result = userRepository.findAllByUsernameInExcludeSelf(Set.of("alpha", "beta"), selfId);

            assertThat(result).extracting(User::getUsername).containsExactly("beta");
            assertThat(result.get(0).getPresence().getStatus()).isEqualTo("IDLE");
            assertThat(statistics.getEntityFetchCount()).isZero();

            statistics.clear();
            // null currentUserId => no self exclusion; a user without a presence row still comes back.
            List<User> all = userRepository.findAllByUsernameInExcludeSelf(Set.of("alpha", "gamma"), null);
            assertThat(all).extracting(User::getUsername).containsExactlyInAnyOrder("alpha", "gamma");
            assertThat(all).allSatisfy(u -> assertThat(u.getPresence()).isNull());
            assertThat(statistics.getEntityFetchCount()).isZero();
        }

        @Test
        void findAccountsDueForPurge_loadsPresenceInTheSameSelect() {
            Instant cutoff = Instant.now().minus(30, ChronoUnit.DAYS);
            User due = user("due");
            due.setDeleted(true);
            due.setDeletionRequestedAt(cutoff.minus(1, ChronoUnit.DAYS));
            User recent = user("recent");
            recent.setDeleted(true);
            recent.setDeletionRequestedAt(cutoff.plus(1, ChronoUnit.DAYS));
            user("active");
            presence(due, "OFFLINE");
            freshContext();

            List<User> result = userRepository.findAccountsDueForPurge(cutoff);

            assertThat(result).extracting(User::getUsername).containsExactly("due");
            assertThat(result.get(0).getPresence().getStatus()).isEqualTo("OFFLINE");
            assertThat(statistics.getEntityFetchCount()).isZero();
        }
    }

    // ── HIB-QUERY-004 ─────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("bulk deletes remove exactly the rows the derived deleteBy methods removed")
    class BulkDeletes {

        @Test
        void deleteByUserAndFeatureKeyAndScopeIn_keepsSelfOptOutAndOtherUsers() {
            User target = user("grantee");
            User other = user("bystander");
            FeatureKey key = FeatureKey.values()[0];
            FeatureKey otherKey = FeatureKey.values()[1];
            em.persist(UserFeatureGrant.builder().user(target).featureKey(key).scope(GrantScope.ADMIN).build());
            em.persist(UserFeatureGrant.builder().user(target).featureKey(key).scope(GrantScope.COHORT).build());
            em.persist(UserFeatureGrant.builder().user(target).featureKey(key).scope(GrantScope.SELF).build());
            em.persist(UserFeatureGrant.builder().user(target).featureKey(otherKey).scope(GrantScope.ADMIN).build());
            em.persist(UserFeatureGrant.builder().user(other).featureKey(key).scope(GrantScope.ADMIN).build());
            freshContext();

            userFeatureGrantRepository.deleteByUserAndFeatureKeyAndScopeIn(
                    target, key, EnumSet.of(GrantScope.ADMIN, GrantScope.COHORT));
            em.clear();

            List<UserFeatureGrant> remaining = em.createQuery("select g from UserFeatureGrant g", UserFeatureGrant.class).getResultList();
            assertThat(remaining).hasSize(3);
            assertThat(remaining).filteredOn(g -> g.getUser().getId().equals(target.getId()) && g.getFeatureKey() == key)
                    .extracting(UserFeatureGrant::getScope).containsExactly(GrantScope.SELF);
        }

        @Test
        void deleteByWeekStartBefore_prunesOnlyOlderWeeks() {
            User a = user("wa");
            User b = user("wb");
            LocalDate monday = LocalDate.of(2026, 8, 31);
            em.persist(WeeklyMatchPick.builder().user(a).pickedUser(b).score(1).rank(1).weekStart(monday.minusWeeks(2)).build());
            em.persist(WeeklyMatchPick.builder().user(a).pickedUser(b).score(1).rank(1).weekStart(monday.minusWeeks(1)).build());
            em.persist(WeeklyMatchPick.builder().user(a).pickedUser(b).score(1).rank(1).weekStart(monday).build());
            freshContext();

            weeklyMatchPickRepository.deleteByWeekStartBefore(monday);
            em.clear();

            List<WeeklyMatchPick> remaining = em.createQuery("select p from WeeklyMatchPick p", WeeklyMatchPick.class).getResultList();
            assertThat(remaining).extracting(WeeklyMatchPick::getWeekStart).containsExactly(monday);
        }

        @Test
        void deleteByEndpoint_removesOnlyThatEndpoint() {
            User u = user("pusher");
            em.persist(PushSubscription.builder().user(u).endpoint("https://push/a").p256dh("k").auth("a")
                    .installationType(InstallationType.PWA).build());
            em.persist(PushSubscription.builder().user(u).endpoint("https://push/b").p256dh("k").auth("a")
                    .installationType(InstallationType.PWA).build());
            freshContext();

            pushSubscriptionRepository.deleteByEndpoint("https://push/a");
            em.clear();

            assertThat(pushSubscriptionRepository.findAll()).extracting(PushSubscription::getEndpoint)
                    .containsExactly("https://push/b");
        }

        @Test
        void userExperience_deleteByUser_removesOnlyThatUsersRows() {
            User u = user("exp1");
            User other = user("exp2");
            em.persist(UserExperience.builder().user(u).tag("hiking").build());
            em.persist(UserExperience.builder().user(u).tag("chess").build());
            em.persist(UserExperience.builder().user(other).tag("hiking").build());
            freshContext();

            userExperienceRepository.deleteByUser(u);
            em.clear();

            List<UserExperience> remaining = userExperienceRepository.findAll();
            assertThat(remaining).hasSize(1);
            assertThat(remaining.get(0).getUser().getId()).isEqualTo(other.getId());
        }

        @Test
        void session_deleteByUser_removesOnlyThatUsersRows() {
            User u = user("sess1");
            User other = user("sess2");
            em.persist(Session.builder().user(u).userAgent("ua").build());
            em.persist(Session.builder().user(u).userAgent("ua").build());
            em.persist(Session.builder().user(other).userAgent("ua").build());
            freshContext();

            sessionRepository.deleteByUser(u);
            em.clear();

            List<Session> remaining = sessionRepository.findAll();
            assertThat(remaining).hasSize(1);
            assertThat(remaining.get(0).getUser().getId()).isEqualTo(other.getId());
        }

        @Test
        void deleteByMessageAndUser_removesOnlyThatStar() {
            User u = user("star1");
            User other = user("star2");
            Message m1 = message(u);
            Message m2 = message(u);
            em.persist(MessageStar.builder().message(m1).user(u).build());
            em.persist(MessageStar.builder().message(m1).user(other).build());
            em.persist(MessageStar.builder().message(m2).user(u).build());
            freshContext();

            messageStarRepository.deleteByMessageAndUser(m1, u);
            em.clear();

            List<MessageStar> remaining = messageStarRepository.findAll();
            assertThat(remaining).hasSize(2);
            Set<String> keys = new HashSet<>();
            remaining.forEach(s -> keys.add(s.getMessage().getId() + ":" + s.getUser().getId()));
            assertThat(keys).containsExactlyInAnyOrder(m1.getId() + ":" + other.getId(), m2.getId() + ":" + u.getId());
        }
    }

    // ── HIB-ENTITY-009 ────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("@NaturalId on BaseEntity#uuid resolves through the @MappedSuperclass")
    class NaturalId {

        @Test
        void uuidIsAssignedOnPersistAndResolvesAsNaturalId() {
            User u = user("natural");
            assertThat(u.getUuid()).as("@PrePersist assigned the uuid before Hibernate captured state").isNotNull();
            UUID uuid = u.getUuid();
            freshContext();

            User byNaturalId = em.unwrap(org.hibernate.Session.class).bySimpleNaturalId(User.class).load(uuid);

            assertThat(byNaturalId).isNotNull();
            assertThat(byNaturalId.getId()).isEqualTo(u.getId());
            assertThat(byNaturalId.getUsername()).isEqualTo("natural");
        }

        @Test
        void explicitUuidOnANewEntityIsKept() {
            UUID explicit = UUID.randomUUID();
            Chat chat = Chat.builder().build();
            chat.setUuid(explicit);
            persist(chat);
            freshContext();

            assertThat(em.unwrap(org.hibernate.Session.class).bySimpleNaturalId(Chat.class).load(explicit).getId())
                    .isEqualTo(chat.getId());
            assertThat(em.find(Chat.class, chat.getId()).getUuid()).isEqualTo(explicit);
        }
    }

    // ── DB-SCHEMA-001 ─────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Set<Enum> element-collection tables get a composite primary key")
    class ElementCollectionPrimaryKeys {

        private List<String> primaryKeyColumns(String table) throws Exception {
            try (Connection c = dataSource.getConnection();
                 ResultSet rs = c.getMetaData().getPrimaryKeys(null, "PUBLIC", table.toUpperCase(Locale.ROOT))) {
                TreeMap<Integer, String> cols = new TreeMap<>();
                while (rs.next()) {
                    cols.put(rs.getInt("KEY_SEQ"), rs.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
                }
                return new ArrayList<>(cols.values());
            }
        }

        @Test
        void chatTagsUserLanguagesAndUserLookingForHaveAPrimaryKey() throws Exception {
            assertThat(primaryKeyColumns("chat_tags")).containsExactly("chat_id", "tag");
            assertThat(primaryKeyColumns("user_languages")).containsExactly("user_id", "language");
            assertThat(primaryKeyColumns("user_looking_for")).containsExactly("user_id", "tag");
        }

        @Test
        void setElementsStillRoundTrip() {
            User u = user("polyglot");
            u.getLanguages().addAll(Set.of(Language.values()[0], Language.values()[1]));
            u.getLookingFor().add(LookingForTag.values()[0]);
            Chat chat = persist(Chat.builder().build());
            chat.getTags().add(Interest.values()[0]);
            freshContext();

            User reloaded = em.find(User.class, u.getId());
            assertThat(reloaded.getLanguages()).containsExactlyInAnyOrder(Language.values()[0], Language.values()[1]);
            assertThat(reloaded.getLookingFor()).containsExactly(LookingForTag.values()[0]);
            assertThat(em.find(Chat.class, chat.getId()).getTags()).containsExactly(Interest.values()[0]);
        }
    }
}
